# Generated by Django 5.2.5 on 2025-08-17 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('artiste', models.CharField(max_length=100)),
                ('duree', models.DurationField()),
                ('style', models.CharField(max_length=50)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('fichier', models.FileField(upload_to='musiques/')),
                ('publique', models.BooleanField(default=False, help_text='Accessible à tous les utilisateurs')),
                ('utilisateurs_autorises', models.ManyToManyField(blank=True, related_name='musiques_autorisees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
